---
DOMAIN_NAME: cream2018032801071136.saas.appdynamics.com
APPLICATION_NAME: PROD_JAVA_WEB_APPLICATION
TIRE_NAME: PROD_JAVA_TIRE_NAME
NODE_NAME: PROD_NODE_NAME
ACCOUNT_NAME: cream2018032801071136
ACCOUNT_ACCESS_KEY: dwqacfa19d1o